# Generated by Django 2.0.1 on 2018-02-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('reserved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Номера телефонов',
                'verbose_name': 'Номера телефона',
            },
        ),
    ]
