# Generated by Django 2.0.1 on 2018-02-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
