# Generated by Django 2.0.1 on 2018-03-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_phone', '0002_auto_20180218_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumbersFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='', verbose_name='Выберите файл')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы с номерами',
            },
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
    ]
